default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>

development:
  <<: *default
  database: employee_portal_development

test:
  <<: *default
  database: employee_portal_test

production:
  <<: *default
  database: employee_portal_production
  username: employee_portal
  password: <%= ENV["EMPLOYEE_PORTAL_DATABASE_PASSWORD"] %>
